### ISSUE TITLE
Trackpad?

### ISSUE THREAD

**Issue by tonyvsuk** [CremBluRay/ASUS-ROG-GL552VW-HACKINTOSH#1]
Thanks for this, I've used it successfully to get OSX onto an Asus GL502VT.

You mention the trackpad works, how did you get it working?

Thanks in advance,

Tony.

**Comment by tonyvsuk** [comment]
If it helps, I've done a bit of research. It's an ELAN1200 trackpad.

I'd try to find the kexts myself but am still waiting on a new larger SSD drive from Amazon.

**Comment by CremBluRay** [comment]
That helps a lot. The tonymac forums have a lot of resources, so I'll start there.

**Comment by CremBluRay** [comment]
Ok, I found a guide on how to get touchpad working. It's not too difficult, but it requires a little work. https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/TouchPad-with-VoodooI2C

**Comment by tonyvsuk** [comment]
An update for anyone with a GL502VT laptop.

I had been following the guide mentioned above. Tried following the instructions to the point where they mention the GPIO pin. Mine is 0x11 which I read elsewhere (cannot remember where) that VoodooI2C kext should work. Plus 0x11 is not in the coreboot list. So I backed up my Clover installation, then downloaded the latest VoodooI2C release (2.2). Navigated to /Volumes/EFI/EFI/CLOVER/kexts/Other and replaced the existing VoodooI2C.kext and VoodooI2CHID.kext with the latest release. Reboot, and now my touchpad works when it boots into OSX. It doesn't work during boot, but I'm fine with that.

Hope this helps.

Thanks again and again to CremBluRay for this. I've got a fully working machine now.

**Comment by ramandika** [comment]
Hey @tonyvsuk my laptop model is GL552VW but I have 0x11 GPIO pin as well. I have tried your way of updating the kexts, unfortunately no luck for me. What mojave version are you? I am on 10.14.6. Does the version matter in this case?

**Comment by tonyvsuk** [comment]
Not sure what to suggest @ramandika. I've got no idea if the version of OSX matters, as soon as mine started working, I stopped trying anything else. My laptop is a GL502VT, I did not have to go through the instructions for the GL552.

**Comment by ramandika** [comment]
> Not sure what to suggest @ramandika. I've got no idea if the version of OSX matters, as soon as mine started working, I stopped trying anything else. My laptop is a GL502VT, I did not have to go through the instructions for the GL552.

is the gesture also works? 2-3 fingers gestures.. What mojave version are you now on?

**Comment by tonyvsuk** [comment]
I'm running 10.14.6. I know two finger scrolling works, I don't use any other of the gestures.

**Comment by ramandika** [comment]
Mind to share your EFi @tonyvsuk ? Really appreciate it

**Comment by tonyvsuk** [comment]
I don't know how to share the EFI.

I've got a different laptop anyway, the set of instructions to get your touchpad working are quite complicated.
